version: "3"

vars:
  MODEL: gemma3:1b

tasks:
  default:
    cmd: task -a

  fmt:
    cmds:
      - isort .
      - black .

  run:
    dir: src/core
    cmd: uv run main.py

  local:ollama:serve:
    cmd: ollama serve

  local:ollama:model:pull:
    cmd: ollama pull {{.MODEL}}

  local:ollama:model:run:
    cmd: ollama run {{.MODEL}}
