[project]
name = "core"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "langchain-community>=0.3.21",
    "langchain-ollama>=0.3.2",
    "mypy>=1.15.0",
]
